### ISSUE TITLE
penalize impossible poses

### ISSUE THREAD

**Issue by yyvettey** [nghorbani/human_body_prior#11]
Hi, I am curious how I can use VPoser to penalize impossible smpl body_pose (63-dim paramters). 

The encoder takes the angles and outputs a distribution. Can I expect the encoded distribution to be mean=0 std=1 for valid pose?

**Comment by nghorbani** [comment]
Hi, the encoder of a VAE produces a latent code Z given the input X, e.g. P(Z|X). so if now the input is a distorted one you might still get a plausible code. so that is not useful for abnormality detection out-of-the-box. Alternatively, I can imagine what you could do is to decode the Z with the decoder and try to reconstruct the input. Now if the reconstruction is too far from the input, by some means of distance, then you can argue that the input was an anomaly.
